apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.secret_name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cloudmeter-secret-store
    kind: SecretStore
  target:
    name: {{ .Values.secrets.secret_name }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.secrets.aws_path }}