name: Update Portfolio Secrets

on:
  workflow_dispatch:
    inputs:
      lock_id:
        description: "Update AWS Secrets"
        required: true

jobs:
  update-secrets:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x apps/portfolio/update-secrets.sh

      - name: Run update secrets script
        run: ./apps/portfolio/update-secrets.sh
